### PR TITLE
Add: support for multiple networks

### LINKED ISSUE #19: BSCScan
Does the plugin work with BSCscan?

Getting "Cannot verify in the selected network" error

### LINKED ISSUE #36: please add chainid support
https://github.com/Machinalabs/remix-etherscan-plugin/blob/0e6e88783560f93ea3b5cd5f7adce6d04ce9edb1/src/utils/utilities.ts#L7

works correct localy for 43114:

export const getEtherScanApi = (network: string) => {
  return network === "custum"
    ? `https://api.snowtrace.io/api`
    : `https://api-${network}.snowtrace.io/api`
}

should be the same for other etherscan supported chains

### LINKED ISSUE #59: Add support for other explorer same as Etherscan
As there are many blockchain using same explorer service of Etherscan Ex: BSCScan, Polygonscan. Need support for them too.

### PR DESCRIPTION
**Pull request by MonarthS**
Added support for these explorers:

Mainnet:

1. [bscscan.com](https://bscscan.com)
2. [polygonscan.com](https://polygonscan.com)
3. [ftmscan.com](https://ftmscan.com)
4. [arbiscan.io](https://arbiscan.io)
5. [snowtrace.io](https://snowtrace.io)
6. [moonriver.moonscan.io](https://moonriver.moonscan.io)
7. [moonbeam.moonscan.io](https://moonbeam.moonscan.io)
8. [bttcscan.com](https://bttcscan.com)

Testnet:

1. [testnet.bscscan.com](https://testnet.bscscan.com)
2. [mumbai.polygonscan.com](https://mumbai.polygonscan.com)
3. [testnet.ftmscan.com](https://testnet.ftmscan.com)
4. [testnet.arbiscan.io](https://testnet.arbiscan.io)
5. [testnet.snowtrace.io](https://testnet.snowtrace.io)
6. [moonbase.moonscan.io](https://moonbase.moonscan.io)
7. [testnet.cronoscan.com](https://testnet.cronoscan.com)
8. [testnet.bttcscan.com](https://testnet.bttcscan.com)

closes #59, closes #19, closes #36

### CODE REVIEW

**Review by pasevin — APPROVED** [review]

**Comment by pasevin** [comment]
Please merge this :)

**Review by sgilflores3 — APPROVED** [review]

**Comment by deutschefi** [comment]
Wen

**Comment by deutschefi** [comment]
Someone with write access @EdsonAlcala

**Comment by deutschefi** [comment]
Some hack I'm using is,

1. Use the current plugin, 
2. Open network tab in browser dev tools
3. Apply for verify contract
4. API request will fail
5. Open the failed request (in red color)
6. In request parameters, find the JSON encoded source code item and copy it
7. Create new .json file with this contents
8. Go to bscscan or elsewhere
9. On verify contract page select 'JSON encoded input' option
10. Upload the file created in step 7
11. It'll verify all contracts neat and clean as solidity multi files

**Comment by theref** [comment]
Please merge this

**Comment by MonarthS** [comment]
Finally, they used my code https://github.com/ethereum/remix-project/commit/abde32bdd69b2817006acdd14c5224bc23a7b05d.

**Comment by EdsonAlcala** [comment]
hey sorry, for not replying on time ! Didn't get any notification, but happy to see that the remix team took the project.

**Pull request closed without merging**
